// src/app/components/nav-bar/Navbar.tsx
'use client';
import { useCallback, useState } from 'react';

import { useTheme } from '../../context/ThemeContext';

const NAVIGATION_ITEMS = [
  { href: '#home', label: 'Home', number: ' 0.' },
  { href: '#about', label: 'About Me', number: ' 1.' },
  { href: '#career', label: 'Career', number: ' 2.' },
  { href: '#project', label: 'Projects', number: ' 3.' },
  { href: '#contact', label: 'Contact', number: ' 4.' },
] as const;

function Navbar() {
  const { toggleTheme, theme } = useTheme();
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = useCallback(() => {
    setIsMenuOpen((prev) => !prev);
  }, []);

  return (
    <header className="fixed top-0 left-0 right-0 bg-white dark:bg-slate-900 border-b border-slate-100 dark:border-slate-800 z-50">
      <div className="max-w-5xl mx-auto px-6">
        <nav className="flex items-center justify-between h-16">
          <button
            onClick={toggleTheme}
            className={`
              font-mono text-sm px-3 py-1.5 rounded-lg 
              border border-slate-200 dark:border-slate-700 
              hover:bg-slate-100 dark:hover:bg-slate-800 
              transition-all duration-300
              text-slate-600 dark:text-slate-400
              focus:outline-none focus:ring-2 focus:ring-slate-400 dark:focus:ring-slate-500
              disabled:cursor-not-allowed
              tracking-wider
            `}
          >
            #{theme === 'light' ? '0F172A' : 'FFFFFF'}
          </button>

          {/* Hamburger Button */}
          <button
            onClick={toggleMenu}
            className="md:hidden p-2 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
            aria-label="Toggle menu"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              {isMenuOpen ? (
                <path d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8 ml-auto">
            {NAVIGATION_ITEMS.map((item) => (
              <a
                key={item.label}
                href={item.href}
                className="group relative text-sm text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
              >
                <span>{item.label}</span>
                <span className="text-slate-400 dark:text-slate-500 group-hover:text-slate-600 dark:group-hover:text-slate-300">
                  {item.number}
                </span>
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-slate-200 dark:bg-slate-700 group-hover:w-full transition-all duration-300"></span>
              </a>
            ))}
          </div>
        </nav>

        {/* Mobile Navigation Menu */}
        <div
          data-testid="mobile-menu"
          className={`md:hidden fixed inset-0 top-16 bg-white dark:bg-slate-900 transition-transform duration-300 ease-in-out ${
            isMenuOpen ? 'translate-y-0' : 'translate-y-full'
          }`}
        >
          <div className="flex flex-col items-center pt-8 gap-8">
            {NAVIGATION_ITEMS.map((item) => (
              <a
                key={item.label}
                href={item.href}
                onClick={toggleMenu}
                className="group text-lg text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
              >
                <span>{item.label}</span>
                <span className="text-slate-400 dark:text-slate-500 group-hover:text-slate-600 dark:group-hover:text-slate-300">
                  {item.number}
                </span>
              </a>
            ))}
          </div>
        </div>
      </div>
    </header>
  );
}

export default Navbar;

// src/components/navbar/Navbar.svelte
<script lang="ts">
  import { FileDown } from "lucide-svelte";
  import { onMount } from "svelte";
  import { fade, slide } from "svelte/transition";
  import { theme } from "../../lib/stores/theme";
  import ThemeControls from "./ThemeControls.svelte";
  import { clickOutside } from './clickOutside';

  let isMenuOpen = false;
  let navItems: {[key: string]: HTMLElement} = {};

  const NAVIGATION_ITEMS = [
    { href: "#home", label: "Home", number: " 0." },
    { href: "#about", label: "About Me", number: " 1." },
    { href: "#career", label: "Career", number: " 2." },
    { href: "#project", label: "Projects", number: " 3." },
    { href: "#contact", label: "Contact", number: " 4." },
  ];

  function handleNavClick(href: string) {
    const element = navItems[href];
    if (element) {
      element.scrollIntoView({ behavior: "smooth" });
      closeMenu();
    }
  }

  function closeMenu() {
    isMenuOpen = false;
  }

  function handleKeyDown(e: KeyboardEvent, href?: string) {
    if (e.key === 'Escape') {
      closeMenu();
      return;
    }
    
    if (href && (e.key === 'Enter' || e.key === ' ')) {
      e.preventDefault();
      handleNavClick(href);
    }
  }

  onMount(() => {
    window.addEventListener('keydown', (e) => handleKeyDown(e));
    return () => {
      window.removeEventListener('keydown', (e) => handleKeyDown(e));
    };
  });
</script>

<style>
  .menu-enter {
    animation: menuEnter 0.2s ease-out;
  }

  @keyframes menuEnter {
    from {
      opacity: 0;
      transform: translateY(-1rem);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>

<header
  class="fixed top-0 left-0 right-0 bg-white dark:bg-slate-900 border-b border-slate-100 dark:border-slate-800 z-50 transition-colors duration-150"
>
  <div class="max-w-5xl mx-auto px-6">
    <nav 
      class="flex items-center justify-between h-16" 
      aria-label="Main navigation"
    >
      <ThemeControls />

      <button
        class="md:hidden p-2 transition-colors mobile-menu text-slate-900 dark:text-white"
        aria-label={isMenuOpen ? "Close navigation menu" : "Open navigation menu"}
        aria-expanded={isMenuOpen}
        aria-controls="mobile-menu"
        on:click|stopPropagation={() => (isMenuOpen = !isMenuOpen)}
      >
        <span class="sr-only">{isMenuOpen ? 'Close Menu' : 'Open Menu'}</span>
        <svg
          class="w-6 h-6"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          {#if isMenuOpen}
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          {:else}
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          {/if}
        </svg>
      </button>

      <!-- Desktop Navigation -->
      <div 
        class="hidden md:flex items-center gap-8" 
        role="menubar"
        aria-label="Desktop navigation menu"
      >
      {#each NAVIGATION_ITEMS as item}
        <a
          href={item.href}
          bind:this={navItems[item.href]}
          on:click|preventDefault={() => handleNavClick(item.href)}
          on:keydown={(e) => handleKeyDown(e, item.href)}
          role="menuitem"
          tabindex="0"
          class="group text-lg transition-colors focus:outline-none focus:ring-2 focus:ring-primary rounded-lg p-2 {$theme.contrast === 'high' 
            ? 'text-slate-900 dark:text-white font-medium' 
            : 'text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'}"
        >
          <span>{item.label}</span>
          <span class="sr-only">Section {item.number}</span>
        </a>
      {/each}
        <a
          href="/levizepeda cv.pdf"
          download
          class="flex items-center gap-2 px-3 py-1.5 text-sm font-medium border rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-primary {$theme.contrast === 'high'
            ? 'border-slate-400 dark:border-slate-500 text-slate-900 dark:text-white hover:bg-slate-200 dark:hover:bg-slate-700'
            : 'border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'}"
          role="button"
          aria-label="Download resume (opens in new tab)"
          tabindex="0"
        >
          <FileDown class="w-5 h-5" aria-hidden="true" />
          <span>Resume</span>
        </a>
      </div>
    </nav>

    <!-- Mobile Menu -->
    {#if isMenuOpen}
    <div
      id="mobile-menu"
      in:fade={{ duration: 150 }}
      out:slide={{ duration: 150 }}
      class="md:hidden fixed inset-0 top-16 bg-white dark:bg-slate-900 z-40"
      role="dialog"
      aria-label="Mobile navigation menu" 
      aria-modal="true"
      use:clickOutside={closeMenu}
    >
      <div class="flex flex-col items-center pt-8 gap-8 menu-enter">
        {#each NAVIGATION_ITEMS as item}
          <a
            href={item.href}
            bind:this={navItems[item.href]}
            on:click|preventDefault={() => handleNavClick(item.href)}
            on:keydown={(e) => handleKeyDown(e, item.href)}
            class="group text-lg transition-colors focus:outline-none focus:ring-2 focus:ring-primary rounded-lg p-2
            {$theme.contrast === 'high'
              ? 'text-slate-900 dark:text-white font-medium'
              : 'text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'}"
            role="menuitem"
            tabindex="0"
          >
            <span>{item.label}</span>
            <span class="sr-only">Section {item.number}</span>
          </a>
        {/each}
      </div>
    </div>
    {/if}
  </div>
</header>
